auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: xiongbanban.com
url: http://xiongbanban.github.io
feed: /atom.xml
author_info: <a href="http://xiongbanban.github.io/">xiongbanban</a>
